# Generated by Django 5.0.4 on 2024-05-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0006_movies_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='dynamic/file/movies/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic/file/music/thumbnails'),
        ),
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='dynamic/file/music/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dynamic/file/music/thumbnails'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='dynamic/file/photos/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='dynamic/file/videos/'),
        ),
    ]
