# Generated by Django 5.0.4 on 2024-05-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0007_alter_movies_file_alter_movies_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='music/thumbnails'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
